apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-demo
  name: spring-boot-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
        - image: vcp.ocir.io/axdfajf0hg0s/spring-boot-demo:latest
          name: spring-boot-demo
          ports:
            - containerPort: 8080