name: Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Build with Gradle
        run: ./gradlew build
        env:
          REGISTRY_IMAGE_URL: ${{ vars.REGISTRY_IMAGE_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Run tests
        run: ./gradlew test

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pushing to Oracle Container Registry
        run: echo "Container image URL:$REGISTRY_IMAGE_URL:${{ github.ref_name }}"
        env:
          REGISTRY_IMAGE_URL: ${{ vars.REGISTRY_IMAGE_URL }}
        
      - name: Build and push container image using Google JIB
        run: ./gradlew jib --image $REGISTRY_IMAGE_URL:${{ github.ref_name }} 
        env:
          REGISTRY_IMAGE_URL: ${{ vars.REGISTRY_IMAGE_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
