name: Build and Deploy

on:
  push:
    tags:
      - '*'

env:
  BASE_IMAGE: amazoncorretto:21.0.3-alpine3.19
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'corretto'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    env:
      REGISTRY_IMAGE_URL: ${{ vars.REGISTRY_IMAGE_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      BASE_IMAGE: amazoncorretto:21.0.3-alpine3.19
      JAVA_VERSION: '21'
      JAVA_DISTRIBUTION: 'corretto'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: $JAVA_VERSION
          distribution: $JAVA_DISTRIBUTION

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
        
      - name: Build and push container image using Google JIB
        run: ./gradlew jib --image $REGISTRY_IMAGE_URL:${{ github.ref_name }} 

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    environment: production
    env:
      K8S_URL: ${{ secrets.K8S_URL }}
      K8S_SECRET: ${{ secrets.K8S_SECRET }}
    steps:
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v4
        with:
           method: service-account
           k8s-url: $K8S_URL
           k8s-secret: $K8S_SECRET

      - name: Deploy to kubernetes cluster
        uses: Azure/k8s-deploy@v5
        with:
           action: deploy
           manifests: |
              infra/deployment.yml
           images: |
              $REGISTRY_IMAGE_URL:${{ github.ref_name }} 

      
